### ISSUE TITLE
Proposte cambiamenti

### ISSUE THREAD

**Issue by elespdn** [CADottorato/sito#1]
- Pubblico: eliminare "Si può proporre di ampliare il pubblico ad altre discipline, nel caso non ci siano abbastanza candidati italianisti alla scadenza delle iscrizioni."
- Pubblico: "La lingua della scuola è l’italiano e si possono accettare interventi di formatori in lingua inglese." --> "La lingua della scuola è l’italiano, ma alcuni materiali, esercizi o interventi possono essere in lingua inglese."
- Formatori: "È prevista inoltre la partecipazione della Prof.ssa Elena Pierazzo (Université Grenoble Alpes)" --> "È prevista inoltre la partecipazione della Prof.ssa Elena Pierazzo (Université Grenoble Alpes) e del Prof. Fabio Ciotti (Università di Roma Tor Vergata, presidente AIUCD)"
- Aggiungere comitato scientifico (Bognolo, Cipolla, Pierazzo, Ciotti)
- Requisiti: "Non sono richieste competenze computazionali. I partecipanti devono tuttavia munirsi di computer portatile + …." --> "Non sono richieste competenze computazionali. <br/>I partecipanti potranno usare i computer messi a disposizione dall'Università di Verona o lavorare sui propri. Nel secondo caso, andranno installati alcuni programmi prima della Summer School, e saranno fornite istruzioni per l'installazione. <br/>Conoscenza della lingua inglese. La lingua della scuola è l’italiano, ma alcuni materiali, esercizi o interventi possono essere in inglese."
- Iscrizioni: "La selezione è volta ad assicurare che il numero dei partecipanti non sia troppo elevato, a discapito della qualità della formazione." --> "La selezione è volta ad assicurare che il numero dei partecipanti non superi il limite di 20, a discapito della qualità della formazione."
- Iscrizioni: "una breve presentazione su come pensi usare le Digital Humanities nel tuo progetto di ricerca, corredata da tre domande di ricerca (max 400 parole);
(opzionale) se già disponibile, un dataset che vorresti trattare con metodi digitali." ---> "una breve presentazione su come si pensa usare le Digital Humanities nel proprio progetto di ricerca, corredata da tre domande di ricerca (max 400 parole);
(opzionale) se già disponibile, un dataset che che si vuole trattare con metodi digitali."

**Comment by gfranzini** [comment]
Fatto!
